import type { Metadata } from "next";
import { Roboto_Slab} from "next/font/google";
import "./globals.css";

const geistSans = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} min-h-screen  antialiased`}
      >
        <div className="min-h-screen absolute top-0 left-0 right-0 opacity-30 max-sm:opacity-40 -z-20"  style={{
      backgroundImage: "url('./img/back.jpg')",
      backgroundSize: 'contain',
      backgroundPosition: 'center',
      
    }}></div>
        {children}
      </body>
    </html>
  );
}
