
import type { Metadata } from "next";
import { Roboto_Slab} from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
// import { SessionProvider } from "next-auth/react";

const geistSans = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} min-h-screen overflow-x-hidden  antialiased`}
      >
        
       <Providers>

          {children}
       </Providers>
       
      </body>
    </html>
  );
}
